# Generated by Django 6.0 on 2025-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_details_product_discounter_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discounter_price',
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
