# Generated by Django 6.0 on 2025-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_product_discounter_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
