# Generated by Django 6.0 on 2026-01-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_details'),
        ('app', '0004_alter_product_details_alter_product_url'),
    ]

    operations = [
    ]
